apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/managed-by: google-cloud-deploy
    deploy.cloud.google.com/delivery-pipeline-id: git-pipeline
    deploy.cloud.google.com/location: us-central1
    deploy.cloud.google.com/project-id: riccardo-blog-test-v1
    deploy.cloud.google.com/release-id: release-003
    deploy.cloud.google.com/target-id: git-dev
  name: getting-started
spec:
  containers:
    - image: nginx:1.14.2
      name: nginx
      ports:
        - containerPort: 80
